### ISSUE TITLE
Data persistence !

### ISSUE THREAD

**Issue by grharry** [bitnami/bitnami-docker-ejbca#5]
I've  encountered a strange behavior. 
`bitnami/ejbca     6    4b27c7ff60cb   `

I am using the default docker-compose.yml with the volumes for ejbca container 

    volumes:
      - "./ejbca_data:/bitnami/ejbca"
and 
for mariadb 
```
  volumes:
      - "./mariadb_data:/bitnami/mariadb"

```
docker-compose up creates the container with no error. 
however 
docker-compose restart breaks and ejbca container exits with code 1

logs show 
---------------------
```
ejbca_1    | 14:04:12,040 ERROR [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0043: Deployment unit processor org.wildfly.extension.microprofile.config.smallrye.deployment.SubsystemDeploymentProcessor@2128c1a9 unexpectedly threw an exception during undeploy phase POST_MODULE of subdeployment "adminweb.war" of deployment "ejbca.ear": java.util.ConcurrentModificationException
ejbca_1    | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
ejbca_1    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
ejbca_1    | 	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
ejbca_1    | 	at io.smallrye.config.SmallRyeConfigProviderResolver.releaseConfig(SmallRyeConfigProviderResolver.java:71)
ejbca_1    | 	at org.wildfly.extension.microprofile.config.smallrye.deployment.SubsystemDeploymentProcessor.undeploy(SubsystemDeploymentProcessor.java:102)
ejbca_1    | 	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.safeUndeploy(DeploymentUnitPhaseService.java:211)
ejbca_1    | 	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.stop(DeploymentUnitPhaseService.java:204)
ejbca_1    | 	at org.jboss.msc.service.ServiceControllerImpl$StopTask.stopService(ServiceControllerImpl.java:1792)
ejbca_1    | 	at org.jboss.msc.service.ServiceControllerImpl$StopTask.execute(ServiceControllerImpl.java:1761)
ejbca_1    | 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
ejbca_1    | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
ejbca_1    | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
ejbca_1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
ejbca_1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
ejbca_1    | 	at java.lang.Thread.run(Thread.java:748)
ejbca_1    | 
ejbca_1    | 14:04:12,107 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0208: Stopped subdeployment (runtime-name: webdist.war) in 569ms
ejbca_1    | 14:04:12,107 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0208: Stopped subdeployment (runtime-name: cesecore-ejb.jar) in 563ms
ejbca_1    | 14:04:12,118 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0208: Stopped subdeployment (runtime-name: clearcache.war) in 569ms
ejbca_1    | 14:04:12,108 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0208: Stopped subdeployment (runtime-name: ejbca-ws-ejb.jar) in 590ms
ejbca_1    | 14:04:12,133 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0208: Stopped subdeployment (runtime-name: scep.war) in 586ms
ejbca_1    | 14:04:12,133 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0208: Stopped subdeployment (runtime-name: cmp.war) in 582ms
ejbca_1    | 14:04:12,135 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0208: Stopped subdeployment (runtime-name: healthcheck.war) in 591ms
ejbca_1    | 14:04:12,135 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0208: Stopped subdeployment (runtime-name: status.war) in 597ms
ejbca_1    | 14:04:12,130 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0208: Stopped subdeployment (runtime-name: ejbca-ejb.jar) in 604ms
ejbca_1    | 14:04:12,131 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0208: Stopped subdeployment (runtime-name: edition-specific-ejb.jar) in 615ms
ejbca_1    | 14:04:12,143 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0008: Undertow HTTPS listener httpspub suspending
ejbca_1    | 14:04:12,144 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTPS listener httpspriv suspending
ejbca_1    | 14:04:12,144 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0008: Undertow HTTP listener remoting suspending
ejbca_1    | 14:04:12,147 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0007: Undertow HTTP listener remoting stopped, was bound to 127.0.0.1:4447
ejbca_1    | 14:04:12,147 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTPS listener httpspriv stopped, was bound to 0.0.0.0:8443
ejbca_1    | 14:04:12,147 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0007: Undertow HTTPS listener httpspub stopped, was bound to 0.0.0.0:8442
ejbca_1    | 14:04:12,147 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0008: Undertow HTTP listener http suspending
ejbca_1    | 14:04:12,151 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0007: Undertow HTTP listener http stopped, was bound to 0.0.0.0:8080
ejbca_1    | 14:04:12,162 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0004: Undertow 2.0.13.Final stopping
ejbca_1    | 14:04:12,162 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0208: Stopped subdeployment (runtime-name: publicweb.war) in 646ms
ejbca_1    | 14:04:12,237 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0208: Stopped subdeployment (runtime-name: ra-gui.war) in 691ms
ejbca_1    | 14:04:12,285 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0208: Stopped subdeployment (runtime-name: doc.war) in 750ms
ejbca_1    | 14:04:12,294 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0208: Stopped subdeployment (runtime-name: adminweb.war) in 776ms
ejbca_1    | 14:04:12,349 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0028: Stopped deployment ejbca.ear (runtime-name: ejbca.ear) in 822ms
ejbca_1    | 14:04:12,366 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: WildFly Full 14.0.1.Final (WildFly Core 6.0.2.Final) stopped in 838ms
ejbca_1    | *** JBossAS process (4344) received TERM signal ***
ejbca_1    | 4344
-----------------------
```

however 
docker-compose down && docker-compose up -d 
Seems to be working 
That is, 
if  the containers  are restarted it breaks down 
If the containers are re-created they seem to be working! 

Is this normal ?? 
Regards
Harry.

**Comment by alvneiayu** [comment]
hi @grharry 

No, this is not normal. This is an issue. I can reproduce your problem. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks to report the issue.

Álvaro

**Comment by fmulero** [comment]
`bitnami/ejbca:6` was deprecated some months ago and no more releases are going to be released for that version.

Please if you reproduce the issue with version 7, open an issue in new [bitnami/containers](https://github.com/bitnami/containers) repository
